server:
  port: 8080

spring:
  application:
    name: crud_base

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
  #    url: ${spring.datasource.url:jdbc:postgresql://localhost:5432/postgres}
  #    username: ${spring.application.name:postgres}
  #    password: ${spring.datasource.password:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
#      host: ${spring.data.redis.host:localhost}
#      port: ${spring.data.redis.port:6379}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    url: /crud_base_openapi.yaml

