server:
  port: 8080

spring:
  application:
    name: crud_base

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    url: /crud_base_openapi.yaml

